# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Your project's server will proxy this localhost address
LOCALHOST: https://wordpress.localhost

SSL:
  status: true
  key: "/opt/homebrew/etc/httpd/certs/localhost-key.pem"
  cert: "/opt/homebrew/etc/httpd/certs/localhost.pem"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}{,/**/*}"
  # Path to theme files
  theme:
    - "src/theme/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
